### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ClosetGeek-Git** [paullouisageneau/violet#12]
Any chance of you licensing violet as LGPL? (like libdatachannel)

**Comment by paullouisageneau** [comment]
What would be the point? LGPL does not make sense for standalone programs.

If you need a LGPL library, you can create a server with [libjuice](https://github.com/paullouisageneau/libjuice) directly.

**Comment by ClosetGeek-Git** [comment]
Thank you @paullouisageneau, it was late in my day and I hadn't given violet's source more than a glance at that point.
