### ISSUE TITLE
Does Violet handles SFU ?

### ISSUE THREAD

**Issue by Rz-Rz** [paullouisageneau/violet#24]
Does Violet handles SFU ? (Room based streaming through a producer/consumers architecture). 
Or maybe I can do that directly using libdatachannel ? I don't know...

**Comment by paullouisageneau** [comment]
Violet is only a STUN/TURN server, it has nothing to do with an SFU. An SFU is a WebRTC agent which forwards streams to other agents, you can indeed implement one with libdatachannel or another WebRTC library.

**Comment by Rz-Rz** [comment]
Thank you for your answer, your time and your awesome projects. I found an SFU example on your libdatachannel github. I will try to adapt it for my use with GStreamer.
