### ISSUE TITLE
Connecting each other via STUN server works only in local network.

### ISSUE THREAD

**Issue by norayrmamulyan53** [paullouisageneau/violet#3]

**Comment by paullouisageneau** [comment]
Could you please provide a description of the failing setup (clients, network topology, Internet connectivity type, etc)? In addition, any sequence of events, logs, or errors messages would be useful (you can run violet with the `--verbose` flag).

**Comment by norayrmamulyan53** [comment]
> Could you please provide a description of the failing setup (clients, network topology, Internet connectivity type, etc)? In addition, any sequence of events, logs, or errors messages would be useful (you can run violet with the `--debug` flag).

I am connecting to STUN server using Javascript and using simple-peer library.
This is configuration.

```Javascript
const DEFAULT_PEER_OPTIONS = {
  initiator: location.hash === '#init',
  trickle: false,
  config: {
    'iceServers': [
      { url: 'stun:91.195.255.172:3478' },
    ]
  }
```
And this is the error.
```
WebRTC: ICE failed, add a TURN server and see about:webrtc for more details
Uncaught Error: Ice connection failed.
    _onIceStateChange index.js:720
    oniceconnectionstatechange index.js:112
index.js:720
Uncaught (in promise) DOMException: The fetching process for the media resource was aborted by the user agent at the user's request.
Uncaught (in promise) DOMException: The fetching process for the media resource was aborted by the user agent at the user's request.
```

**Comment by paullouisageneau** [comment]
Thanks for the elements. What is the Internet connectivity type of the two peers? Are they behind large-scale NAT?

Are the srflx candidates properly generated on both sides? (you can see that on `about:webrtc` in Firefox, or `about:webrtc-internals` in Chrome ). If the srflx candidates are there with the proper IPv4 public addresses, you may be in a situation where each peer is behind a problematic endpoint-dependant (aka symmetric) NAT. In that case, the only way to connect the peers in through a TURN server.

**Comment by norayrmamulyan53** [comment]
> Thanks for the elements. What is the Internet connectivity type of the two peers? Are they behind large-scale NAT?
> 
> Are the srflx candidates properly generated on both sides? (you can see that on `about:webrtc` in Firefox, or `about:webrtc-internals` in Chrome ). If the srflx candidates are there with the proper IPv4 public addresses, you may be in a situation where each peer is behind a problematic endpoint-dependant (aka symmetric) NAT. In that case, the only way to connect the peers in through a TURN server.

* Yes i assume they are behind CGNAT, so can i get around somehow ??

* I gather srflx candidates using either STUN/TURN servers. But i can't make connection even using TURN server - i've set up the violet in the Raspberry PI and have made port mapping (to be seen outside the NAT) . What could be the problem ? 

I can make connections only when they behind the same NAT, using the host candidate. When it comes to STUN/TURN it gives an ICE error (the description is above, plus the TURN server). 

Thanks.

**Comment by paullouisageneau** [comment]
> Yes i assume they are behind CGNAT, so can i get around somehow ??

In that case you need a TURN server.

> I gather srflx candidates using either STUN/TURN servers. But i can't make connection even using TURN server - i've set up the violet in the Raspberry PI and have made port mapping (to be seen outside the NAT) . What could be the problem ?

A TURN server should give you a relay candidate in addition to a srflx one. If there is no relay candidate, then the TURN server is not set up correctly.

The TURN server should ideally be deployed on a machine with open Internet access. Behind a NAT, it could work, but it's a bit tricky: in addition to the server port, you have to redirect the entire UDP relay port range, and set the public IP address in the options (the corresponding option for Violet is `--external`).

Is your TURN server deployed on the same NAT as one of the peers? If you can do port mapping, it's probably not a CGNAT and STUN should actually work.

**Comment by paullouisageneau** [comment]
Any update on this?

**Comment by saroamirkhanyan** [comment]
We could not connect computers outside the LAN

**Comment by saroamirkhanyan** [comment]
We have tried many options but no one has worked, So we have stopped working in that way.

**Comment by paullouisageneau** [comment]
Well in the last message you were trying a very non-conventional setup with a TURN server behind a NAT, I would definitely need more information than "there is an ICE error" to be able to help. I'm closing this then, please re-open if needed.
